# Use the official Python base image
FROM Python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the FastAPI application files to the container
COPY . ./app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that the FastAPI application runs on
EXPOSE 8000

# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
